services:
  postgres:
    image: postgres:15
    container_name: postgtes_pdm
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gerenciador_estabelecimento
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
